### ISSUE TITLE
Parse prEN and FprEN documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-cen#3]
prEN means "draft EN".

```
prEN 12464-1:2019
prEN 13241-1
prEN 13241-1:2013
prEN 14885:2020
prEN 15038:2004
prEN 16942:2016
```

FprEN means "final draft EN".

```
FprEN 16114:2011
FprEN 16798-3
FprEN 50600‑2‑4 
```

**Comment by mico** [comment]
@ronaldtse for pubid-iso we convert "Fpr" to "PRF" (Proof?)

**Comment by mico** [comment]
> @mico I think in pubid-iso maybe we should no longer parse "Fpr", because this is clearly a CEN stage.

Are you sure it's a "draft"? Not the "proof"?
