### ISSUE TITLE
Parse Amendments and Corrigenda

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-cen#4]
```
EN 196-3:2005+A1:2008
EN 527­2:2016+A1:2019
EN 60335-1:2012/A1
EN 60335-1:2012/A14
EN 60335-1:2012/A15
EN 60335-1:2012/A2:2019
EN 60335-1:2012/AC:2014
EN IEC 62368-1:2020+A11:2020 
```

There are 3 types of documents here:
* `/A1` means the document is "Amendment 1"
* `/AC` means the document is "Corrigendum 1".
* `+A1` means this document incorporates "Amendment 1".

**Comment by ronaldtse** [comment]
It looks like EN does not assign corrigenda numbers.

For example, there are:
* EN ISO 13485:2016/AC:2016 (first corrigendum)
* EN ISO 13485:2016/AC:2017 (second corrigendum)
* EN ISO 13485:2016/AC:2018 (third corrigendum)

It is impossible to tell what sequence the a corrigendum is in.

**Comment by mico** [comment]
> It looks like EN does not assign corrigenda numbers.
> 
> For example, there are:
> 
> * EN ISO 13485:2016/AC:2016 (first corrigendum)
> * EN ISO 13485:2016/AC:2017 (second corrigendum)
> * EN ISO 13485:2016/AC:2018 (third corrigendum)
> 
> It is impossible to tell what sequence the a corrigendum is in.

So, we don't store the number? And output will be always like "AC:1234" for corrigendum?

**Comment by ronaldtse** [comment]
> So, we don't store the number? And output will be always like "AC:1234" for corrigendum?

We can store the number but it cannot be rendered. The pattern is always "{base identifier}/AC:yyyy". Clearly when we parse "AC:yyyy" we don't know the corrigendum number, and any accesses that ask for the number should raise an error.

**Comment by mico** [comment]
@ronaldtse could document incorporate corrigendum?
Like `EN 527­2:2016+C1:2019`? Or `EN 527­2:2016+AC:2019`?

**Comment by ronaldtse** [comment]
https://boss.cen.eu/media/abtgvi4x/updating-of-cen-pub.pdf

The official code for a Corrigendum is "AC". There is no "C{n}" pattern in ENs. It is "AC" or "AC1" or "AC2"

<img width="1015" alt="Screenshot 2023-03-29 at 10 38 49 PM" src="https://user-images.githubusercontent.com/11865/228574357-5478eeca-e130-4409-ba7e-a68ebf4fef83.png">

EVS-EN 14891:2012/AC:2012
EVS-EN 14891:2007/AC2:2009
* https://www.evs.ee/en/evs-en-14891-2012
<img width="687" alt="Screenshot 2023-03-29 at 11 12 17 PM" src="https://user-images.githubusercontent.com/11865/228584820-876d9282-8842-4fab-ba61-8f28d680fb41.png">

EN ISO 10077-1:2006+AC:2009+AC2:2009
* https://www.evs.ee/StandardDownload/DownloadPreview?productId=114967&language=EnglishLanguage
<img width="1074" alt="Screenshot 2023-03-29 at 11 13 19 PM" src="https://user-images.githubusercontent.com/11865/228585148-038ee7e7-acdd-4d64-b477-4d8ac7df29eb.png">

EN 196-1:1987/AC2:1989
* https://genorma.com/en/project/show/cen:proj:1195

Additional identifiers
* EVS-EN 934-3:2009+A1:2012
* EVS-EN 934-6:2002/A1:2006

NF EN 13445-2 V1/AC1
* https://cds.cern.ch/record/2048667/files/NF-EN-13445-2-AC1e.pdf
<img width="453" alt="Screenshot 2023-03-29 at 11 06 40 PM" src="https://user-images.githubusercontent.com/11865/228583173-a169e2be-7f4f-4ef4-8bf6-5c2cd61b98a7.png">

NF EN 13445-5 V1/AC1
* https://cds.cern.ch/record/2048675/files/NF-EN-13445-5-AC1e.pdf?subformat=pdfa&version=1
<img width="623" alt="Screenshot 2023-03-29 at 11 06 25 PM" src="https://user-images.githubusercontent.com/11865/228583114-bb392a8e-26a9-411a-8e99-c01d86a684df.png">

NF EN 13445-2 V2/AC2
* https://cds.cern.ch/record/2048667/files/NF-EN-13445-2-AC2e.pdf
<img width="628" alt="Screenshot 2023-03-29 at 11 07 21 PM" src="https://user-images.githubusercontent.com/11865/228583372-d7291a6d-4a71-41a7-bd02-88aef3abe889.png">

SIST EN 61375-2-3:2016/AC2:2017
* https://cdn.standards.iteh.ai/samples/63744/22afa65a580b4da49d002f29a2bf5e99/SIST-EN-61375-2-3-2016-AC2-2017.pdf
<img width="607" alt="Screenshot 2023-03-29 at 11 07 42 PM" src="https://user-images.githubusercontent.com/11865/228583485-dbdd1982-faa6-49e1-8e86-427c18b00750.png">
<img width="865" alt="Screenshot 2023-03-29 at 11 07 48 PM" src="https://user-images.githubusercontent.com/11865/228583507-20a811c4-a40b-4f7d-9845-587da10ab7d2.png">

**Comment by ronaldtse** [comment]
> could document incorporate corrigendum?

Yes, it is given like "EN ISO 10077-1:2006+AC:2009+AC2:2009"
