### ISSUE TITLE
Parse ISO / IEC adoptions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-cen#5]
CEN / CENELEC often adopts ISO or IEC standards.

```
EN ISO 14090:2019
EN ISO 17292
EN ISO 17292:2004
EN IEC 62115:2020 
EN IEC 62368-1:2020
EN IEC 55014-2:2021 
```

**Comment by mico** [comment]
`EN IEC 62368-1:2020+A11:2020` from https://github.com/metanorma/pubid-cen/issues/4

**Comment by mico** [comment]
> EN ISO 13485:2016/AC:2016

@ronaldtse Could be there adopted identifiers with ISO/IEC format supplements?
Like `EN ISO 13485:2016/Amd 1:2016`?
Or it will be always in EN format?

**Comment by ronaldtse** [comment]
@mico yes I believe they use adopted identifiers as-is.
