### ISSUE TITLE
Support CEN/CENELEC identifiers for all document types

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-cen#9]
From https://experts.cen.eu/media/Experts/cen-clc_projex-online_user-guide.pdf

* EN
* HD
* CWA
* TS
* TR
* CG (CEN Guide)

All these documents, except CG can be created with an Amendment / Corrigendum.

**Comment by mico** [comment]
Another source for document types:
https://www.cencenelec.eu/european-standardization/european-standards/types-of-deliverables/

**Comment by ronaldtse** [comment]
Only CWA and HD added in #12, reopening for the rest.

**Comment by ronaldtse** [comment]
Actually they are all supported now. We just don't have enough specs for "CEN Guide".
